services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      elasticsearch:
        condition: service_healthy  
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "9567:9567"
    depends_on:
      - backend

volumes:
  elasticsearch-data:
